language: node_js
node_js:
  - "9"

install:
  - npm ci

script:
  - npm run build

deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  tag: next
  on:
    branch: master
    tags: true
notifications:
  email:
    recipents:
      - $ADMIN_EMAIL
    on_success: always
    on_failure: always
